services:
  backend:
    build: ./backend
    ports:
      - 5001:5001
    volumes:
      - ./backend/src:/app/src
    env_file: ./backend/.env
  db:
    image: postgres
    ports:
      - 5432:5432 
    volumes:
      - /var/lib/postgresql/data
    env_file: .env
  #Adminer pour PostGreSQL : gestion de la bdd
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
